parsifal/account_settings/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('parsifal.account_settings.views',
    url(r'^$', 'settings', name='settings'),
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^emails/$', 'emails', name='emails'),
    url(r'^picture/$', 'picture', name='picture'),
    url(r'^password/$', 'password', name='password'),

    url(r'^connections/$', 'connections', name='connections'),
    
    url(r'^mendeley_connection/$', 'mendeley_connection', name='mendeley_connection'),
    url(r'^connect_mendeley/$', 'connect_mendeley', name='connect_mendeley'),
    url(r'^disconnect_mendeley/$', 'disconnect_mendeley', name='disconnect_mendeley'),

    url(r'^dropbox_connection/$', 'dropbox_connection', name='dropbox_connection'),
    url(r'^connect_dropbox/$', 'connect_dropbox', name='connect_dropbox'),
    url(r'^disconnect_dropbox/$', 'disconnect_dropbox', name='disconnect_dropbox'),

    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

parsifal/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('parsifal',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='core/about.html'), name='about'),
    url(r'^signup/$', 'authentication.views.signup', name='signup'),
    url(r'^signin/$', 'authentication.views.signin', name='signin'),
    url(r'^signout/$', 'authentication.views.signout', name='signout'),
    url(r'^reset/$', 'authentication.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'authentication.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'authentication.views.success', name='success'),
    url(r'^reviews/', include('parsifal.reviews.urls', namespace='reviews')),
    url(r'^activity/', include('parsifal.activities.urls', namespace='activities')),
    url(r'^blog/', include('parsifal.blog.urls', namespace='blog')),
    url(r'^help/', include('parsifal.help.urls', namespace='help')),
    url(r'^library/', include('parsifal.library.urls', namespace='library')),
    url(r'^settings/', include('parsifal.account_settings.urls', namespace='settings')),
    url(r'^review_settings/transfer/$', 'reviews.settings.views.transfer', name='transfer_review'),
    url(r'^review_settings/delete/$', 'reviews.settings.views.delete', name='delete_review'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^(?P<username>[^/]+)/following/$', 'activities.views.following', name='following'),
    url(r'^(?P<username>[^/]+)/followers/$', 'activities.views.followers', name='followers'),

    # Review URLs
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/$', 'reviews.views.review', name='review'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/settings/$', 'reviews.settings.views.settings', name='settings'),
    
    # Planning Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/$', 'reviews.planning.views.planning', name='planning'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/protocol/$', 'reviews.planning.views.protocol', name='protocol'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/quality/$', 'reviews.planning.views.quality_assessment_checklist', name='quality_assessment_checklist'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/extraction/$', 'reviews.planning.views.data_extraction_form', name='data_extraction_form'),

    # Conducting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/$', 'reviews.conducting.views.conducting', name='conducting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/search/$', 'reviews.conducting.views.search_studies', name='search_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/import/$', 'reviews.conducting.views.import_studies', name='import_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/studies/$', 'reviews.conducting.views.study_selection', name='study_selection'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/quality/$', 'reviews.conducting.views.quality_assessment', name='quality_assessment'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/extraction/$', 'reviews.conducting.views.data_extraction', name='data_extraction'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/analysis/$', 'reviews.conducting.views.data_analysis', name='data_analysis'),

    # Reporting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/$', 'reviews.reporting.views.reporting', name='reporting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/export/$', 'reviews.reporting.views.export', name='export'),

    url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parsifal/account_settings/models.py
from django.db import models

# Create your models here.

parsifal/reviews/settings/models.py
from django.db import models

# Create your models here.

parsifal/reviews/settings/forms.py
# coding: utf-8

from django import forms

from parsifal.reviews.models import Review


class ReviewSettingsForm(forms.ModelForm):
    name = forms.SlugField(
            widget=forms.TextInput(attrs={ 'class': 'form-control' }), 
            label='URL',
            help_text='Only letters, numbers, underscores or hyphens are allowed.',
            max_length=255)

    class Meta:
        model = Review
        fields = ['name',]

parsifal/account_settings/views.py
# coding: utf-8

import os
from PIL import Image
from mendeley.session import MendeleySession
from oauthlib.oauth2 import TokenExpiredError
from dropbox.client import DropboxClient, DropboxOAuth2Flow

from django.core.urlresolvers import reverse as r
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.conf import settings as django_settings
from django.contrib.auth import update_session_auth_hash

from parsifal.account_settings.forms import UserEmailForm, ProfileForm, PasswordForm


@login_required
def settings(request):
    return redirect('/settings/profile/')

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, u'Your profile were successfully edited.')
            return redirect(r('settings:profile'))
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'settings/profile.html', { 'form': form })

@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET['upload_picture'] == 'uploaded':
            uploaded_picture = True
    except Exception, e:
        uploaded_picture = False
    return render(request, 'settings/picture.html', { 'uploaded_picture': uploaded_picture })

@login_required
def emails(request):
    if request.method == 'POST':
        form = UserEmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, u'Account Email changed successfully.')
        else:
            messages.error(request, u'Please correct the error below.')
    else:
        form = UserEmailForm(instance=request.user)
    return render(request, 'settings/emails.html', { 'form' : form })

@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u'Password changed successfully.')
            update_session_auth_hash(request, form.user)
        else:
            messages.error(request, u'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'settings/password.html', { 'form' : form })


@login_required
def upload_picture(request):
    try:
        f = request.FILES['picture']
        ext = os.path.splitext(f.name)[1].lower()
        valid_extensions = ['.gif', '.png', '.jpg', '.jpeg', '.bmp']
        if ext in valid_extensions:
            filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
            with open(filename, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            im = Image.open(filename)
            width, height = im.size
            if width > 560:
                new_width = 560
                new_height = (height * 560) / width
                new_size = new_width, new_height
                im.thumbnail(new_size, Image.ANTIALIAS)
                im.save(filename)
            return redirect('/settings/picture/?upload_picture=uploaded')
        else:
            messages.error(request, u'Invalid file format.')
    except Exception, e:
        messages.error(request, u'An expected error occurred.')
    return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST['x'])
        y = int(request.POST['y'])
        w = int(request.POST['w'])
        h = int(request.POST['h'])
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)
        return HttpResponse(django_settings.MEDIA_URL + 'profile_pictures/' + request.user.username + '.jpg')
    except Exception, e:
        return HttpResponseBadRequest()

def get_dropbox_auth_flow(session):
    return DropboxOAuth2Flow(
            django_settings.DROPBOX_APP_KEY,
            django_settings.DROPBOX_SECRET,
            django_settings.DROPBOX_REDIRECT_URI,
            session,
            'dropbox-auth-csrf-token')

@login_required
def connections(request):
    return render(request, 'settings/connections.html')

@login_required
def mendeley_connection(request):
    mendeley_profile = request.user.profile.get_mendeley_profile()
    mendeley_profile_picture = None
    if not mendeley_profile:
        mendeley = django_settings.MENDELEY
        auth = mendeley.start_authorization_code_flow()
        mendeley_auth_url = auth.get_login_url()
    else:
        mendeley_profile_picture = mendeley_profile.photo.square
        mendeley_profile_picture = mendeley_profile_picture.replace('http://', 'https://')
        mendeley_auth_url = ''
    return render(request, 'settings/includes/mendeley_connection.html', {
            'mendeley_auth_url': mendeley_auth_url,
            'mendeley_profile': mendeley_profile,
            'mendeley_profile_picture': mendeley_profile_picture
            })

@login_required
def dropbox_connection(request):
    dropbox_profile = request.user.profile.get_dropbox_profile()
    if not dropbox_profile:
        dropbox_auth_url = get_dropbox_auth_flow(request.session).start()
    else:
        dropbox_auth_url = ''
    return render(request, 'settings/includes/dropbox_connection.html', {
            'dropbox_auth_url': dropbox_auth_url,
            'dropbox_profile': dropbox_profile
            })

@login_required
def connect_mendeley(request):
    if 'code' in request.GET and 'state' in request.GET:
        code = request.GET.get('code')
        state = request.GET.get('state')
        mendeley = django_settings.MENDELEY
        auth = mendeley.start_authorization_code_flow(state=state)
        auth_path = u'{0}?code={1}&state={2}'.format(django_settings.MENDELEY_REDIRECT_URI, code, state)
        mendeley_session = auth.authenticate(auth_path)
        request.user.profile.set_mendeley_token(mendeley_session.token)
        request.user.save()
        messages.success(request, 'Your Mendeley account were linked successfully!')
    else:
        messages.error(request, 'A problem occurred while trying to connect your Mendeley account.')
    return redirect(r('settings:connections'))

@login_required
def disconnect_mendeley(request):
    if request.method == 'POST':
        request.user.profile.mendeley_token = None
        request.user.save()
        messages.success(request, 'Your Mendeley account were disconnected successfully!')
    return redirect(r('settings:connections'))

@login_required
def connect_dropbox(request):
    try:
        access_token, user_id, url_state = get_dropbox_auth_flow(request.session).finish(request.GET)
        messages.success(request, u'Your Dropbox account were linked successfully!')
        request.user.profile.dropbox_token = access_token
        request.user.save()
    except DropboxOAuth2Flow.NotApprovedException, e:
        messages.warning(request, 'You didn\'t approved Parsifal to connect your Dropbox account.')
    except Exception, e:
        messages.error(request, 'A problem occurred while trying to connect your Dropbox account. Please try again later.')
    return redirect(r('settings:connections'))

@login_required
def disconnect_dropbox(request):
    if request.method == 'POST':
        dropbox_token = request.user.profile.dropbox_token
        if dropbox_token is not None:
            client = DropboxClient(dropbox_token)
            client.disable_access_token()
            request.user.profile.dropbox_token = None
            request.user.save()
            messages.success(request, 'Your Dropbox account were disconnected successfully!')
    return redirect(r('settings:connections'))

parsifal/reviews/settings/views.py
# coding: utf-8

from django.core.urlresolvers import reverse as r
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect, render
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseBadRequest
from django.template.defaultfilters import slugify
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST

from parsifal.reviews.models import Review
from parsifal.reviews.decorators import main_author_required
from parsifal.reviews.settings.forms import ReviewSettingsForm


@main_author_required
@login_required
def settings(request, username, review_name):
    review = Review.objects.get(name=review_name, author__username__iexact=username)
    if request.method == 'POST':
        form = ReviewSettingsForm(request.POST, instance=review)
        if form.is_valid():
            name = slugify(form.instance.name)
            unique_name = name
            if unique_name != review_name:
                i = 0
                while Review.objects.filter(name=unique_name, author__username=review.author.username):
                    i = i + 1
                    unique_name = u'{0}-{1}'.format(name, i)
            form.instance.name = unique_name
            review = form.save()
            messages.success(request, u'Review was saved successfully.')
            return redirect(r('settings', args=(review.author.username, unique_name)))
    else:
        form = ReviewSettingsForm(instance=review)
    return render(request, 'settings/review_settings.html', { 
            'review': review,
            'form': form
            })


@main_author_required
@login_required
def transfer(request):
    try:
        review_id = request.POST['review-id']
        transfer_user_username = request.POST['transfer-user']
        review = Review.objects.get(pk=review_id)
        try:
            transfer_user = User.objects.get(username=transfer_user_username)
        except Exception, e:
            return HttpResponseBadRequest('User not found.')
        current_user = request.user
        if current_user != transfer_user:
            if transfer_user in review.co_authors.all():
                review.co_authors.remove(transfer_user)
            review.author = transfer_user
            review.co_authors.add(current_user)
            review.save()
            return HttpResponse('/' + review.author.username + '/' + review.name + '/')
        else:
            return HttpResponseBadRequest('Hey! You can\'t transfer the review to yourself.')
    except Exception, e:
        return HttpResponseBadRequest('Something went wrong.')


@main_author_required
@login_required
@require_POST
def delete(request):
    review_id = request.POST.get('review-id')
    review = Review.objects.get(pk=review_id)
    username = review.author.username
    sources = review.sources.all()
    for source in sources:
        if not source.is_default:
            review.sources.remove(source)
            source.delete()
    review.delete()
    messages.success(request, u'The review was deleted successfully.')
    return redirect(r('reviews', args=(review.author.username,)))

parsifal/account_settings/templates/settings/connections.html
{% extends 'base.html' %}

{% block title %}Account Settings · Parsifal{% endblock %}

{% block javascript %}
  <script>
    $(function () {

      $.fn.loadConnection = function (url) {
        var url = $(this).attr("data-remote");
        var container = $(this);
        $.ajax({
          url: url,
          cache: false,
          beforeSend: function () {
            $(container).spinner(false);
            $(".block-spinner", container).addClass("pull-right");
          },
          success: function (data) {
            $(container).html(data);
          },
          complete: function () {
            $(container).spinner();
          }
        });
      };

      $(".mendeley-container").loadConnection();
      $(".dropbox-container").loadConnection();

    });
  </script>
{% endblock javascript %}

{% block content %}  
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Connected Services</h3>
        </div>
        <ul class="list-group">
          <li class="list-group-item">
            <h4>Connect to Mendeley</h4>
            <div class="row">
              <div class="col-xs-8">
                <p>Import your references from Mendeley. Associate your Mendeley library to your reviews. Friends you have on Mendeley who are also on Parsifal will become part of your Parsifal network.</p>
              </div>
              <div class="col-xs-4 text-right mendeley-container" data-remote="{% url 'settings:mendeley_connection' %}">

              </div>
            </div>
          </li>
          <li class="list-group-item">
            <h4>Connect to Dropbox</h4>
            <div class="row">
              <div class="col-xs-8">
                <p>Use your Dropbox account as your personal library and store papers related to your literature reviews.</p>
              </div>
              <div class="col-xs-4 text-right dropbox-container" data-remote="{% url 'settings:dropbox_connection' %}">

              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

parsifal/account_settings/templates/settings/emails.html
{% extends 'base.html' %}

{% block title %}Account Settings · Parsifal{% endblock %}

{% block content %}  
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form action="{% url 'settings:emails' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Account email</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success btn-large">Save email</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

parsifal/account_settings/templates/settings/password.html
{% extends 'base.html' %}

{% block title %}Account Settings · Parsifal{% endblock %}

{% block content %}  
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Change password</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success">Change password</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

parsifal/account_settings/templates/settings/picture.html
{% extends 'base.html' %}

{% block title %}Account Settings · Parsifal{% endblock %}

{% load staticfiles %}

{% block stylesheet %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <style>
    .jcrop-keymgr {
      display: none!important;
    }
  </style>
{% endblock stylesheet %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'js/jquery.Jcrop.min.js' %}?_=1"></script>
  <script type="text/javascript" src="{% static 'js/profile.js' %}?_=1"></script>
  <script>
    {% if uploaded_picture %}
      $(function () {
        $("#modal-upload-picture").modal('show');
        window.history.pushState("", "", "/settings/picture/");
      });
    {% endif %}
  </script>
{% endblock javascript %}

{% block content %}  
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form enctype="multipart/form-data" method="post" action="{% url 'settings:upload_picture' %}" id="picture-upload-form" class="form-block">
        {% csrf_token %}
        <input type="file" name="picture" class="hide">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Profile picture</h3>
          </div>
          <div class="panel-body">
            <img src="{{ user.profile.get_picture }}" style="width: 200px;" class="thumbnail profile-picture">
          </div>
          <div class="panel-footer">
            <button type="button" class="btn btn-primary" id="btn-upload-picture">Upload new picture</button>
          </div>
        </div>

        <div class="modal fade" id="modal-upload-picture">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Crop Profile Picture</h4>
              </div>
              <div class="modal-body">
                {% if uploaded_picture %}
                  <div class="selected-picture">
                    <p>Crop the profile picture and then click on the <strong>Save Picture</strong> button</p>
                    <img src="{{ MEDIA_URL }}/profile_pictures/{{ request.user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x">
                    <input type="hidden" id="y" name="y">
                    <input type="hidden" id="w" name="w">
                    <input type="hidden" id="h" name="h">
                  </div>
                {% endif %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success btn-save-picture">Save picture</button>
              </div>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
{% endblock content %}

parsifal/account_settings/templates/settings/profile.html
{% extends 'base.html' %}

{% block title %}Account Settings · Parsifal{% endblock %}

{% block content %}  
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form action="{% url 'settings:profile' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Edit Profile ({{ user.username }})</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success btn-large">Save profile</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

parsifal/account_settings/templates/settings/settings_menu.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Account settings</h3>
  </div>
  <div class="list-group">
    <a href="{% url 'settings:profile' %}" class="list-group-item">Profile</a>
    <a href="{% url 'settings:emails' %}" class="list-group-item">Emails</a>
    <a href="{% url 'settings:picture' %}" class="list-group-item">Picture</a>
    <a href="{% url 'settings:password' %}" class="list-group-item">Password</a>
    {% comment %}<a href="{% url 'settings:connections' %}" class="list-group-item">Connected services</a>{% endcomment %}
  </div>
</div>