parsifal/library/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

urlpatterns = patterns('parsifal.library.views',
    url(r'^$', 'index', name='index'),
    url(r'^list_actions/$', 'list_actions', name='list_actions'),
    url(r'^new_folder/$', 'new_folder', name='new_folder'),
    url(r'^edit_folder/$', 'edit_folder', name='edit_folder'),
    url(r'^folders/(?P<slug>[-\w]+)/$', 'folder', name='folder'),
    url(r'^new_shared_folder/$', 'new_shared_folder', name='new_shared_folder'),
    url(r'^shared/(?P<slug>[-\w]+)/$', 'shared_folder', name='shared_folder'),
    url(r'^new_document/$', 'new_document', name='new_document'),
    url(r'^documents/(?P<document_id>\d+)/$', 'document', name='document'),
    url(r'^move/$', 'move', name='move'),
    url(r'^copy/$', 'copy', name='copy'),
    url(r'^remove_from_folder/$', 'remove_from_folder', name='remove_from_folder'),
    url(r'^delete_documents/$', 'delete_documents', name='delete_documents'),
    url(r'^import_bibtex/$', 'import_bibtex', name='import_bibtex'),
)

parsifal/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('parsifal',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='core/about.html'), name='about'),
    url(r'^signup/$', 'authentication.views.signup', name='signup'),
    url(r'^signin/$', 'authentication.views.signin', name='signin'),
    url(r'^signout/$', 'authentication.views.signout', name='signout'),
    url(r'^reset/$', 'authentication.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'authentication.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'authentication.views.success', name='success'),
    url(r'^reviews/', include('parsifal.reviews.urls', namespace='reviews')),
    url(r'^activity/', include('parsifal.activities.urls', namespace='activities')),
    url(r'^blog/', include('parsifal.blog.urls', namespace='blog')),
    url(r'^help/', include('parsifal.help.urls', namespace='help')),
    url(r'^library/', include('parsifal.library.urls', namespace='library')),
    url(r'^settings/', include('parsifal.account_settings.urls', namespace='settings')),
    url(r'^review_settings/transfer/$', 'reviews.settings.views.transfer', name='transfer_review'),
    url(r'^review_settings/delete/$', 'reviews.settings.views.delete', name='delete_review'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^(?P<username>[^/]+)/following/$', 'activities.views.following', name='following'),
    url(r'^(?P<username>[^/]+)/followers/$', 'activities.views.followers', name='followers'),

    # Review URLs
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/$', 'reviews.views.review', name='review'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/settings/$', 'reviews.settings.views.settings', name='settings'),
    
    # Planning Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/$', 'reviews.planning.views.planning', name='planning'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/protocol/$', 'reviews.planning.views.protocol', name='protocol'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/quality/$', 'reviews.planning.views.quality_assessment_checklist', name='quality_assessment_checklist'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/extraction/$', 'reviews.planning.views.data_extraction_form', name='data_extraction_form'),

    # Conducting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/$', 'reviews.conducting.views.conducting', name='conducting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/search/$', 'reviews.conducting.views.search_studies', name='search_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/import/$', 'reviews.conducting.views.import_studies', name='import_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/studies/$', 'reviews.conducting.views.study_selection', name='study_selection'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/quality/$', 'reviews.conducting.views.quality_assessment', name='quality_assessment'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/extraction/$', 'reviews.conducting.views.data_extraction', name='data_extraction'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/analysis/$', 'reviews.conducting.views.data_analysis', name='data_analysis'),

    # Reporting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/$', 'reviews.reporting.views.reporting', name='reporting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/export/$', 'reviews.reporting.views.export', name='export'),

    url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parsifal/library/views.py
# coding: utf-8

import json
import os
import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.customization import convert_to_unicode

from django.db import transaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse as r
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

from parsifal.reviews.models import Review, Article
from parsifal.library.models import Folder, Document
from parsifal.library.forms import FolderForm, DocumentForm, SharedFolderForm


def get_order(request):
    order = request.GET.get('o', '').lower()
    if order in ['title', '-title', 'author', '-author', 'year', '-year']:
        return order
    return 'title'

def get_paginated_documents(request, queryset):
    paginator = Paginator(queryset, 100)
    page = request.GET.get('p')
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        documents = paginator.page(1)
    except EmptyPage:
        documents = paginator.page(paginator.num_pages)
    return documents

def get_filtered_documents(queryset, querystring):
    if querystring:
        queryset = queryset.filter(title__icontains=querystring)
    return queryset

def library(request, documents, querystring, order, active_folder=None):
    reviews = Review.objects.filter(author=request.user)
    folder_form = FolderForm(initial={ 'user': request.user })
    shared_folder_form = SharedFolderForm()
    current_full_path = request.get_full_path()
    return render(request, 'library/library.html', { 
            'reviews': reviews, 
            'documents': documents,
            'querystring': querystring,
            'order': order,
            'active_folder': active_folder,
            'folder_form': folder_form,
            'shared_folder_form': shared_folder_form,
            'current_full_path': current_full_path
        })

@login_required
def index(request):
    querystring = request.GET.get('q', '')
    order = get_order(request)
    queryset = Document.objects.filter(user=request.user)
    queryset = get_filtered_documents(queryset, querystring)
    queryset = queryset.order_by(order)
    documents = get_paginated_documents(request, queryset)
    return library(request, documents, querystring, order)

@login_required
@require_POST
def list_actions(request):
    action = request.POST.get('action')
    if action == 'remove_from_folder':
        return remove_from_folder(request)
    elif action == 'delete_documents':
        return delete_documents(request)
    elif action == 'move':
        return move(request)
    elif action == 'copy':
        return copy(request)
    redirect_to = request.POST.get('redirect', r('library:index'))
    return redirect(redirect_to)

@login_required
def folder(request, slug):
    querystring = request.GET.get('q', '')
    order = get_order(request)
    folder = get_object_or_404(Folder, slug=slug)
    queryset = folder.documents.all()
    queryset = get_filtered_documents(queryset, querystring)
    queryset = queryset.order_by(order)
    documents = get_paginated_documents(request, queryset)
    return library(request, documents, querystring, order, folder)

@login_required
@require_POST
def new_folder(request):
    form = FolderForm(request.POST)
    if form.is_valid():
        form.instance.user = request.user
        folder = form.save()
        dump = json.dumps({ 'folder': { 'id': folder.id, 'name': folder.name, 'slug': folder.slug } })
        return HttpResponse(dump, content_type='application/json')
    else:
        dump = json.dumps(form.errors)
        return HttpResponseBadRequest(dump, content_type='application/json')

@login_required
@require_POST
def edit_folder(request):
    delete_folder = request.POST.get('delete', '') == 'delete'
    folder_id = request.POST.get('id')
    folder = Folder.objects.get(pk=folder_id)
    if delete_folder:
        folder.delete()
        messages.success(request, u'The folder {0} was deleted successfully!'.format(folder.name))
        return redirect(r('library:index'))
    else:    
        form = FolderForm(request.POST, instance=folder)
        if form.is_valid():
            form.instance.user = request.user
            folder = form.save()
            messages.success(request, u'The folder {0} was changed successfully!'.format(folder.name))
        else:
            messages.error(request, u'An error ocurred while trying to save folder {0}'.format(folder.name))
    return redirect(r('library:folder', args=(folder.slug,)))

@login_required
def document(request, document_id):
    document = Document.objects.get(pk=document_id)
    json_context = {}
    if request.method == 'POST':
        form = DocumentForm(request.POST, instance=document)
        if form.is_valid():
            document = form.save()
            json_context['status'] = 'success'
            json_context['html'] = render_to_string('library/partial_document_summary.html', { 'document': document })
            return HttpResponse(json.dumps(json_context), content_type='application/json')
        else:
            json_context['status'] = 'error'
    else:
        form = DocumentForm(instance=document)
        json_context['status'] = 'ok'
    csrf_token = unicode(csrf(request)['csrf_token'])
    json_context['html'] = render_to_string('library/document.html', { 'form': form, 'csrf_token': csrf_token })
    return HttpResponse(json.dumps(json_context), content_type='application/json')

@login_required
def new_document(request):
    json_context = {}
    if request.method == 'POST':
        form = DocumentForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            document = form.save()
            messages.success(request, 'Document added successfully!')
            json_context['status'] = 'success'
            json_context['redirect_to'] = r('library:index')
        else:
            json_context['status'] = 'error'
    else:
        form = DocumentForm()
        json_context['status'] = 'ok'
    csrf_token = unicode(csrf(request)['csrf_token'])
    html = render_to_string('library/new_document.html', { 'form': form, 'csrf_token': csrf_token })
    json_context['html'] = html
    dump = json.dumps(json_context)
    return HttpResponse(dump, content_type='application/json')

def get_document_verbose_name(documents_size):
    document_verbose_name = 'document'
    if documents_size > 1:
        document_verbose_name = 'documents'
    return document_verbose_name

@login_required
@require_POST
def move(request):
    move_from_folder_id = request.POST.get('active-folder-id')
    move_from_folder = Folder.objects.get(pk=move_from_folder_id)

    move_to_folder_id = request.POST.get('action-folder-id')
    move_to_folder = Folder.objects.get(pk=move_to_folder_id)

    if request.POST.get('select-all-pages') == 'all':
        documents = move_from_folder.documents.all()
    else:
        document_ids = request.POST.getlist('document')
        documents = Document.objects.filter(id__in=document_ids)

    querystring = request.POST.get('querystring', '')
    documents = get_filtered_documents(documents, querystring)

    move_to_folder.documents.add(*documents)
    move_from_folder.documents.remove(*documents)

    messages.success(request, u'Documents moved from folder {0} to {1} successfully!'.format(move_from_folder.name, move_to_folder.name))
    redirect_to = request.POST.get('redirect', r('library:index'))
    return redirect(redirect_to)

@login_required
@require_POST
def copy(request):
    redirect_to = request.POST.get('redirect', r('library:index'))

    copy_from_folder_id = request.POST.get('active-folder-id')
    copy_to_folder_id = request.POST.get('action-folder-id')

    try:
        copy_to_folder = Folder.objects.get(pk=copy_to_folder_id)
    except Folder.DoesNotExist:
        messages.error(u'The folder you are trying to copy does not exist.')
        return redirect(redirect_to)

    select_all_pages = request.POST.get('select-all-pages')
    document_ids = request.POST.getlist('document')

    if copy_from_folder_id:
        try:
            copy_from_folder = Folder.objects.get(pk=copy_from_folder_id)
            documents = copy_from_folder.documents.all()
        except Folder.DoesNotExist:
            messages.error(u'The folder you are trying to copy does not exist.')
            return redirect(redirect_to)
    else:
        documents = Document.objects.filter(user=request.user)

    if select_all_pages == 'all':
        querystring = request.POST.get('querystring', '')
        documents = get_filtered_documents(documents, querystring)
    else:
        documents = documents.filter(id__in=document_ids)

    copy_to_folder.documents.add(*documents)
    messages.success(request, u'Documents copied to folder {0} successfully!'.format(copy_to_folder.name))
    return redirect(redirect_to)

@login_required
@require_POST
def remove_from_folder(request):
    remove_from_folder_id = request.POST.get('active-folder-id')
    folder = Folder.objects.get(pk=remove_from_folder_id)
    select_all_pages = request.POST.get('select-all-pages')

    if select_all_pages == 'all':
        querystring = request.POST.get('querystring', '')
        documents = folder.documents.all()
        documents = get_filtered_documents(documents, querystring)
        documents_size = documents.count()
        folder.documents.remove(*documents)
    else:
        documents = request.POST.getlist('document')
        documents_size = len(documents)
        folder.documents.remove(*documents)

parsifal/library/templates/library/document.html
<div class="modal-content">
  <form id="form-document" action="{% url 'library:document' form.instance.pk %}" method="post" data-document-id="{{ form.instance.pk }}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Document details</h4>
    </div>
    <div class="modal-body">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#details" aria-controls="details" role="tab" data-toggle="tab">Details</a></li>
        <li role="presentation"><a href="#files" aria-controls="files" role="tab" data-toggle="tab">Files</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="details">
          {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
              {{ field }}
              {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
              {% endfor %}
              <span class="help-block">{{ field.help_text }}</span>
            </div>
          {% endfor %}
        </div>
        <div role="tabpanel" class="tab-pane" id="files"></div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <button type="button" class="btn btn-success js-save-document">Save changes</button>
    </div>
  </form>
</div>

parsifal/library/templates/library/edit_folder.html
<form id="form-folder-settings" method="post" action="{% url 'library:edit_folder' %}">
  {% csrf_token %}
  <input type="hidden" name="id" value="{{ folder.id }}">
  <div class="modal fade" id="modal-folder-settings">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">{{ folder.name }} Settings</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" name="name" class="form-control" value="{{ folder.name }}">
          </div>
          <div class="form-group">
            <div class="checkbox">
              <label>
                <input type="checkbox" name="delete" value="delete" autocomplete="off">
                Delete this folder
              </label>
            </div>
            <span class="help-block">The associated documents won't be deleted.</span>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-success">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</form>

parsifal/library/templates/library/library.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
{% if active_folder %}
{{ active_folder.name }}
{% else %}
Library · Parsifal
{% endif %}
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/library.js' %}"></script>
{% endblock %}

{% block mustache %}
  {% verbatim %}
    <script id="folder-action-template" type="x-tmpl-mustache">
      <li>
        <a href="javascript:void(0);" class="{{ css_class }}" data-to-folder-id="{{ to }}" data-from-folder-id="{{ from }}">{{ name }}</a>
      </li>
    </script>
  {% endverbatim %}
{% endblock %}

{% block content %}
  <h2 class="page-header">
    My Library
    <a href="#" class="pull-right btn btn-primary"><span class="glyphicon glyphicon-cog"></span> Library settings</a>
  </h2>

  <div class="row">
    <div class="col-md-4 col-lg-3">
      {% include 'library/includes/menu.html' with reviews=reviews folder_form=folder_form %}
    </div>
    <div class="col-md-8 col-lg-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <form action="." method="get" id="search-form">
            <input type="hidden" name="o" value="{{ order }}">
            <div class="input-group pull-right" style="width: 300px; font-weight: normal; margin-top: -6px;">
              <input type="text" name="q" class="form-control input-sm" placeholder="Search" value="{{ querystring }}">
              <span class="input-group-btn">
                {% if querystring %}
                  <a href="." class="btn btn-default btn-sm" data-toggle="tooltip" title="Clear search" data-placement="bottom" data-container="body">
                    <span class="glyphicon glyphicon-remove"></span>
                  </a>
                {% endif %}
                <button class="btn btn-default btn-sm" type="submit" data-toggle="tooltip" title="Search" data-placement="bottom" data-container="body">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </form>
          <h3 class="panel-title">
            {% if active_folder %}
              <span class="glyphicon glyphicon-folder-close" style="margin-right: 5px;"></span> {{ active_folder.name }}
            {% else %}
              <span class="glyphicon glyphicon-inbox" style="margin-right: 5px;"></span> All documents
            {% endif %}
          </h3>
        </div>
        <div class="panel-body">
          {% include 'library/includes/toolbar.html' with documents=documents active_folder=active_folder %}
        </div>
        <form id="form-library" method="post" action="{% url 'library:list_actions' %}">
          {% csrf_token %}
          <input type="hidden" name="action" id="library-action">
          <input type="hidden" name="select-all-pages" id="select-all-pages" value="">
          <input type="hidden" name="querystring" value="{{ querystring }}">
          <input type="hidden" name="action-folder-id" id="action-folder-id" value="">
          <input type="hidden" name="active-folder-id" id="active-folder-id" value="{{ active_folder.pk }}">
          <input type="hidden" name="redirect" value="{{ current_full_path }}">
          <table class="table table-hover" id="library-documents" data-num-pages="{{ documents.paginator.num_pages }}" data-num-documents="{{ documents.object_list.count }}">
            <tbody>
              <tr class="bg-warning text-center js-message-select-all-pages" style="display: none;">
                <td colspan="2">
                  All <strong>{{ documents.object_list.count }}</strong> documents selected on this page.
                  {% if documents.paginator.num_pages > 1 %}
                    <a href="javascript:void(0);" class="js-select-all-documents">Select all <strong>{{ documents.paginator.count }}</strong> documents in this folder.</a>
                  {% endif %}
                </td>
              </tr>
              <tr class="bg-warning text-center js-message-clear-selection" style="display: none;">
                <td colspan="2">
                  All <strong>{{ documents.paginator.count }}</strong> documents selected in this folder.
                  <a href="javascript:void(0);" class="js-clear-selection">Clear selection.</a>
                </td>
              </tr>
              {% for document in documents %}
                <tr data-id="{{ document.id }}">
                  <td style="text-align: center; vertical-align: middle; width: 35px;" class="js-document-checkbox">
                    <span class="glyphicon glyphicon-unchecked"></span>
                    <input type="checkbox" name="document" class="hide" value="{{ document.pk }}" autocomplete="off">
                  </td>
                  <td class="js-document-details">
                    {% include 'library/partial_document_summary.html' with document=document %}
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2" class="empty-library">
                    {% if querystring %}
                      <span class="glyphicon glyphicon-search"></span>
                      <h4>The search returned no result.</h4>
                      <a href="." class="btn btn-default">Clear search</a>
                    {% else %}
                      <span class="glyphicon glyphicon-duplicate"></span>
                      <h4>There are no documents in this folder.</h4>
                      <button type="button" class="btn btn-primary js-new-document"><span class="glyphicon glyphicon-plus"></span> Add a document</button>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </form>
      </div>
    </div>
  </div>

  {% include 'library/edit_folder.html' with folder=active_folder %}

  <div class="modal fade" id="modal-document" data-remote-url="{% url 'library:new_document' %}">
    <div class="modal-dialog modal-lg"></div>
  </div>
{% endblock %}

parsifal/library/templates/library/new_document.html
<div class="modal-content">
  <form id="form-new-document" action="{% url 'library:new_document' %}" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Add document</h4>
    </div>
    <div class="modal-body">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#details" aria-controls="details" role="tab" data-toggle="tab">Details</a></li>
        <li role="presentation"><a href="#files" aria-controls="files" role="tab" data-toggle="tab">Files</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="details">
          {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
              {{ field }}
              {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
              {% endfor %}
              <span class="help-block">{{ field.help_text }}</span>
            </div>
          {% endfor %}
        </div>
        <div role="tabpanel" class="tab-pane" id="files"></div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <button type="button" class="btn btn-success js-save-new-document">Save changes</button>
    </div>
  </form>
</div>

parsifal/library/templates/library/new_folder.html
<form id="form-new-folder" action="{% url 'library:new_folder' %}" method="post">
  {% csrf_token %}
  {{ form.user }}
  <div class="form-group has-feedback{% if form.name.errors %} has-error{% endif %}" style="margin-bottom: 0;">
    {{ form.name  }}
    <span class="form-control-feedback" aria-hidden="true" style="display: none;"></span>
    <span class="errors"></span>
  </div>
</form>

parsifal/library/templates/library/new_shared_folder.html
<form id="form-new-shared-folder" action="{% url 'library:new_shared_folder' %}" method="post">
  {% csrf_token %}
  <div class="form-group has-feedback{% if form.name.errors %} has-error{% endif %}" style="margin-bottom: 0;">
    {{ form.name  }}
    <span class="form-control-feedback" aria-hidden="true" style="display: none;"></span>
    <span class="errors"></span>
  </div>
</form>

parsifal/library/templates/library/partial_document_summary.html
<p style="margin: 0;">{{ document.title }}{% if document.year %} ({{ document.year }}){% endif %}</p>
{% if document.author or document.journal %}
  <p style="margin-top: 5px; margin-bottom: 0;">
    {% if document.author %}<span>{{ document.author }}</span>{% if document.journal %},{% endif %}{% endif %}
    {% if document.journal %} <strong>{{ document.journal }}</strong>.{% endif %}
    {% if document.doi %} doi: <a href="http://dx.doi.org/{{ document.doi }}" target="_blank"><small>{{ document.doi }}&nbsp;<span class="glyphicon glyphicon-new-window"></span></small></a>{% endif %}
  </p>
{% endif %}