parsifal/help/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

urlpatterns = patterns('parsifal.help.views',
    url(r'^$', 'articles', name='articles'),
    url(r'^search/$', 'search', name='search'),
    url(r'^(?P<slug>[-\w]+)/$', 'article', name='article'),
)

parsifal/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('parsifal',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='core/about.html'), name='about'),
    url(r'^signup/$', 'authentication.views.signup', name='signup'),
    url(r'^signin/$', 'authentication.views.signin', name='signin'),
    url(r'^signout/$', 'authentication.views.signout', name='signout'),
    url(r'^reset/$', 'authentication.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'authentication.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'authentication.views.success', name='success'),
    url(r'^reviews/', include('parsifal.reviews.urls', namespace='reviews')),
    url(r'^activity/', include('parsifal.activities.urls', namespace='activities')),
    url(r'^blog/', include('parsifal.blog.urls', namespace='blog')),
    url(r'^help/', include('parsifal.help.urls', namespace='help')),
    url(r'^library/', include('parsifal.library.urls', namespace='library')),
    url(r'^settings/', include('parsifal.account_settings.urls', namespace='settings')),
    url(r'^review_settings/transfer/$', 'reviews.settings.views.transfer', name='transfer_review'),
    url(r'^review_settings/delete/$', 'reviews.settings.views.delete', name='delete_review'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^(?P<username>[^/]+)/following/$', 'activities.views.following', name='following'),
    url(r'^(?P<username>[^/]+)/followers/$', 'activities.views.followers', name='followers'),

    # Review URLs
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/$', 'reviews.views.review', name='review'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/settings/$', 'reviews.settings.views.settings', name='settings'),
    
    # Planning Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/$', 'reviews.planning.views.planning', name='planning'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/protocol/$', 'reviews.planning.views.protocol', name='protocol'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/quality/$', 'reviews.planning.views.quality_assessment_checklist', name='quality_assessment_checklist'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/extraction/$', 'reviews.planning.views.data_extraction_form', name='data_extraction_form'),

    # Conducting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/$', 'reviews.conducting.views.conducting', name='conducting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/search/$', 'reviews.conducting.views.search_studies', name='search_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/import/$', 'reviews.conducting.views.import_studies', name='import_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/studies/$', 'reviews.conducting.views.study_selection', name='study_selection'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/quality/$', 'reviews.conducting.views.quality_assessment', name='quality_assessment'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/extraction/$', 'reviews.conducting.views.data_extraction', name='data_extraction'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/analysis/$', 'reviews.conducting.views.data_analysis', name='data_analysis'),

    # Reporting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/$', 'reviews.reporting.views.reporting', name='reporting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/export/$', 'reviews.reporting.views.export', name='export'),

    url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parsifal/help/models.py
from bs4 import BeautifulSoup

from django.db import models
from django.contrib.auth.models import User

from parsifal.core.models import Media


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, null=True)

    class Meta:
        verbose_name = u'Category'
        verbose_name_plural = u'Categories'

    def __unicode__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    content = models.TextField(max_length=4000, null=True, blank=True)
    references = models.TextField(max_length=2000, null=True, blank=True)
    category = models.ForeignKey(Category)
    views = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    parent = models.ForeignKey(u'Article', null=True, blank=True)
    medias = models.ManyToManyField(Media, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name=u'help_article_creation_user')
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, null=True, related_name=u'help_article_update_user')

    class Meta:
        verbose_name = u'Article'
        verbose_name_plural = u'Articles'

    def __unicode__(self):
        return self.title

    def raw_content(self):
        soup = BeautifulSoup(self.content)
        return soup.get_text()

parsifal/search/models.py
from django.db import models

# Create your models here.

parsifal/help/views.py
# coding: utf-8

from django.core.urlresolvers import reverse as r
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

from parsifal.help.models import Article


def articles(request):
    articles = Article.objects.filter(is_active=True).order_by('category__name', 'title',)
    return render(request, 'help/articles.html', { 'articles': articles })

def article(request, slug):
    article = get_object_or_404(Article, slug=slug, is_active=True)
    article.views += 1
    article.save()
    return render(request, 'help/article.html', { 'article': article })

def search(request):
    if 'q' in request.GET:
        querystring = request.GET.get('q').strip()
        if querystring:
            articles = Article.objects \
                    .filter(is_active=True) \
                    .filter(Q(title__icontains=querystring) | Q(content__icontains=querystring)) \
                    .order_by('title')
            return render(request, 'help/search.html', { 'articles': articles, 'querystring': querystring })
    return redirect(r('help:articles'))

parsifal/search/views.py
from django.shortcuts import render

# Create your views here.

parsifal/help/templates/help/article.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ article.category.name }} · {{ article.title }}{% endblock %}

{% block meta %}
<meta name="Description" content="{{ article.raw_content|truncatechars:'255' }}">
<meta property="og:type" content="article" />
<meta property="og:title" content="{{ article.title }}" />
<meta property="og:description" content="{{ article.raw_content|truncatechars:'255' }}" />
{% for media in article.medias.all %}
{{ media.get_fb_og_metatags|safe }}
{% endfor %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><a href="{% url 'help:articles' %}">Help</a></li>
        <li><a href="{% url 'help:articles' %}#{{ article.category.slug }}">{{ article.category.name }}</a></li>
        <li class="active">{{ article.title }}</li>
      </ol>
      <article>
        <h2 class="page-header">{{ article.title }}</h2>
        {{ article.content|safe }}
      </article>
      <hr>
      <p>If you didn't find what you were looking for, contact us <a href="mailto:support@parsif.al">support@parsif.al</a>.</p>
    </div>
  </div>
{% endblock content %}

parsifal/help/templates/help/articles.html
{% extends 'base.html' %}

{% block title %}Help · Parsifal{% endblock %}

{% block fullwidthheader %}
  <div class="masthead">
    <h1>Help</h1>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
          <form action="{% url 'help:search' %}" method="get">
            <div class="input-group">
              <input type="text" name="q" class="form-control input-lg" placeholder="Search">
              <span class="input-group-btn">
                <button class="btn btn-default btn-lg" type="submit">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      {% regroup articles by category as category_list %}
      {% for category in category_list %}
        <div class="panel panel-default" id="{{ category.grouper.slug }}">
          <div class="panel-heading">
            <h3 class="panel-title">{{ category.grouper.name }}</h3>
          </div>
          <div class="list-group">
            {% for article in category.list %}
              <a href="{% url 'help:article' article.slug %}" class="list-group-item">{{ article.title }}</a>
            {% endfor %}
          </div>
        </div>
      {% endfor %}   
      <hr>
      <p>If you didn't find what you were looking for, contact us <a href="mailto:support@parsif.al">support@parsif.al</a>.</p>
    </div>
  </div>
{% endblock content %}

parsifal/help/templates/help/search.html
{% extends 'base.html' %}

{% block title %}Help · Parsifal{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="page-header">
        <form action="{% url 'help:search' %}" method="get">
          <div class="input-group pull-right" style="width: 300px; font-weight: normal;">
            <input type="text" name="q" class="form-control" placeholder="Search" value="{{ querystring }}">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>
          </div>
        </form>
        Search Result
      </h2>
      <article>
        {% for article in articles %}
          <h3><a href="{% url 'help:article' article.slug %}">{{ article.title }}</a></h3>
          <p>{{ article.raw_content|truncatechars:'255' }}</p>
          <hr>
        {% endfor %}
      </article>
      <p>If you didn't find what you were looking for, contact us <a href="mailto:support@parsif.al">support@parsif.al</a>.</p>
    </div>
  </div>
{% endblock content %}